# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('like_count', models.IntegerField(default=0)),
                ('info', models.TextField()),
            ],
            options={
                'ordering': ('login',),
            },
        ),
    ]
